from sqlalchemy import Column, Integer, String, Numeric, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class User(Base):
    """
    User profile table linking to customer_id from Open Finance transaction feed.
    """
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, unique=True, index=True, nullable=False)  # From MA Open Banking
    name = Column(String(255), nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    primary_geo_location = Column(String(255), nullable=True)  # City, Country format
    latitude = Column(Numeric(10, 8), nullable=True)
    longitude = Column(Numeric(11, 8), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    preferences = relationship("UserPreference", back_populates="user", uselist=False)
    transactions = relationship("Transaction", back_populates="user")


class UserPreference(Base):
    """
    User preferences for notifications, geo-location, and auto-apply settings.
    """
    __tablename__ = "user_preferences"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    notifications_enabled = Column(Boolean, default=True)
    priceless_geo_location = Column(String(255), nullable=True)  # City/region for Priceless experiences
    priceless_notifications_enabled = Column(Boolean, default=True)
    auto_apply_rewards_enabled = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    user = relationship("User", back_populates="preferences")


class Transaction(Base):
    """
    Transaction History Schema
    
    Date Time Fields: Posted (by FI) and Transaction date/time fields available.
    Customer ID: A number generated by MA Open Banking that uniquely identifies a customer.
    Account ID: A number generated by MA Open Banking that uniquely identifies a customer's account: checking, savings, etc.
    Description + Memo: Two free text fields, often concatenated by data science, that offer information on merchant, payment processor, geographic location, and transaction type (P2P, P2M, Income, etc).
    Value Amount: In USD.
    """
    __tablename__ = "transactions"
    
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, nullable=False, index=True)  # From MA Open Banking
    account_id = Column(Integer, nullable=False, index=True)  # From MA Open Banking
    posted_at = Column(DateTime(timezone=True), nullable=False, index=True)  # Posted by FI
    transaction_at = Column(DateTime(timezone=True), nullable=False)  # Transaction date/time
    description = Column(Text, nullable=False)  # Free text field
    memo = Column(Text, nullable=True)  # Free text field
    value_amount_usd = Column(Numeric(12, 2), nullable=False)  # In USD
    
    # Normalized/enriched fields (added by data processing)
    merchant_normalized = Column(String(255), nullable=True, index=True)
    category = Column(String(100), nullable=True, index=True)  # dining, travel, groceries, etc.
    location_inferred = Column(String(255), nullable=True)
    
    # Reward matching fields
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    matched_reward_id = Column(Integer, ForeignKey("rewards.id"), nullable=True)
    reward_applied = Column(Boolean, default=False)
    reward_savings_amount = Column(Numeric(12, 2), nullable=True)  # USD saved from this transaction
    notification_triggered = Column(Boolean, default=False)  # Whether user acted on notification
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    user = relationship("User", back_populates="transactions")
    reward = relationship("Reward", foreign_keys=[matched_reward_id])


class Reward(Base):
    """
    Rewards Data (Merchants & Offers)
    Supports various reward types including cashback, fixed amounts, and Priceless experiences.
    """
    __tablename__ = "rewards"
    
    id = Column(Integer, primary_key=True, index=True)
    merchant_name = Column(String(255), nullable=False, index=True)
    merchant_id = Column(String(100), nullable=True)  # External merchant ID if needed
    external_id = Column(String(100), nullable=True)  # External reward ID
    
    reward_type = Column(String(50), nullable=False)  # percentage_cashback, fixed_amount, experience, other
    reward_label = Column(String(255), nullable=False)  # e.g., "5% back at Coffee Shops"
    reward_description = Column(Text, nullable=True)
    category = Column(String(100), nullable=True, index=True)  # dining, travel, groceries, entertainment
    terms = Column(Text, nullable=True)
    
    start_date = Column(DateTime(timezone=True), nullable=False)
    end_date = Column(DateTime(timezone=True), nullable=True)
    max_savings_amount = Column(Numeric(12, 2), nullable=True)  # Optional max savings cap
    
    # Geo-scope: global, country, city, geofence, etc.
    geo_scope = Column(String(50), default="global")  # global, country, city, geofence
    geo_country = Column(String(100), nullable=True)
    geo_city = Column(String(100), nullable=True)
    geo_latitude = Column(Numeric(10, 8), nullable=True)
    geo_longitude = Column(Numeric(11, 8), nullable=True)
    geo_radius_km = Column(Numeric(10, 2), nullable=True)  # For geofence
    
    is_auto_applicable = Column(Boolean, default=False)  # Can be auto-applied
    requires_user_opt_in = Column(Boolean, default=False)  # Requires explicit user action
    
    # Reward calculation fields
    percentage_value = Column(Numeric(5, 2), nullable=True)  # For percentage_cashback
    fixed_amount_value = Column(Numeric(12, 2), nullable=True)  # For fixed_amount
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

